name: CTS Build Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository_owner}}/${{github.repository}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: add execute flag to build.sh
        working-directory: ./frontend
        run: chmod +x build.sh

      - name: Build the Docker image
        working-directory: ./frontend
        env:
        run: |
          ./build.sh
        ## Pushing to gitHub docker registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CTS_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag the Docker image
        # ToDo: change to correct Path
        run: docker tag cts-frontend ghcr.io/your-user/nuxt-starter:latest
        working-directory: ./frontend

      - name: Push the Docker image
        # ToDo: change to correct Path
        run: docker push ghcr.io/your-user/nuxt-starter:latest
        working-directory: ./frontend